import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Primitives from "@/components/threejs-primitives"
import SceneGraph from "@/components/scenegraph"
import Tank from "@/components/tank"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`} style={{ display: "flex", flexWrap: "wrap", gap: "10px" }}>
        <Primitives />
        <SceneGraph />
        <Tank />
      </main>
    </>
  )
}
